config/routes.rb
Rails.application.routes.draw do
  root "robots#index"

  resources :robots, only: [:index, :show, :new, :create, :edit, :update]

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  belongs_to :robot
end

app/models/robot.rb
class Robot < ActiveRecord::Base
  has_many :abilities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def index
    @robots = Robot.all
  end

  def show
    @robot = Robot.find(params[:id])
  end

  def new
    @robot = Robot.new
  end

  def create
    robot = Robot.create(name: robot_params[:name])
    robot.abilities.create(name: robot_params[:abilities])
    if robot.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @robot = Robot.find(params[:id])
  end

  def update
    robot = Robot.find(params[:id])
    robot.update(name: robot_params[:name])
    robot.abilities.delete_all
    robot.abilities.create(name: robot_params[:abilities])
    redirect_to root_path
  end

  private

  def robot_params
    params.require(:robot).permit(:name, :abilities)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Robots</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/robots/edit.html.erb
<%= form_for(@robot) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :abilities %>
<%= f.text_field :abilities %>
<%= f.submit %>
<% end %>

app/views/robots/index.html.erb
<% @robots.each do |robot| %>
  <%= link_to "#{robot.name}", robot_path(robot.id) %><%= button_to "Edit #{robot.name}", edit_robot_path(robot.id), method: :get %>
<% end %>
<%= link_to "Create Robot", new_robot_path %>

app/views/robots/new.html.erb
<%= form_for(@robot) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :abilities %>
  <%= f.text_field :abilities %>
  <%= f.submit "Create Robot" %>
<% end %>

app/views/robots/show.html.erb
Abilities: <% @robot.abilities.each do |robot_ability| %>
  <%= robot_ability.name %>
<% end %>